//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowerShoppingEntities : DbContext
    {
        public FlowerShoppingEntities()
            : base("name=FlowerShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Log_Types> Log_Types { get; set; }
        public virtual DbSet<LoginLog> LoginLogs { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Products_Categories_Mapping> Products_Categories_Mapping { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<System_Logs> System_Logs { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<LevelPermission> LevelPermissions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Shipping> Shippings { get; set; }
        public virtual DbSet<Product_Logs> Product_Logs { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Disable> Disables { get; set; }
    }
}
