//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime TimeLogin { get; set; }
        public bool IsLogin { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
