//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ShippingId { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
        public decimal ShippingFee { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Receiver { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> CouponId { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual Status Status { get; set; }
    }
}
